//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spark.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool startOnBoot {
            get {
                return ((bool)(this["startOnBoot"]));
            }
            set {
                this["startOnBoot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool startMinimized {
            get {
                return ((bool)(this["startMinimized"]));
            }
            set {
                this["startMinimized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool autoRestart {
            get {
                return ((bool)(this["autoRestart"]));
            }
            set {
                this["autoRestart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool capturevp2 {
            get {
                return ((bool)(this["capturevp2"]));
            }
            set {
                this["capturevp2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool showDatabaseLog {
            get {
                return ((bool)(this["showDatabaseLog"]));
            }
            set {
                this["showDatabaseLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool discordRichPresence {
            get {
                return ((bool)(this["discordRichPresence"]));
            }
            set {
                this["discordRichPresence"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool logToServer {
            get {
                return ((bool)(this["logToServer"]));
            }
            set {
                this["logToServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string echoVRPath {
            get {
                return ((string)(this["echoVRPath"]));
            }
            set {
                this["echoVRPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string echoVRIP {
            get {
                return ((string)(this["echoVRIP"]));
            }
            set {
                this["echoVRIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6721")]
        public int echoVRPort {
            get {
                return ((int)(this["echoVRPort"]));
            }
            set {
                this["echoVRPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool enableStatsLogging {
            get {
                return ((bool)(this["enableStatsLogging"]));
            }
            set {
                this["enableStatsLogging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int targetDeltaTimeIndexStats {
            get {
                return ((int)(this["targetDeltaTimeIndexStats"]));
            }
            set {
                this["targetDeltaTimeIndexStats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool uploadToIgniteDB {
            get {
                return ((bool)(this["uploadToIgniteDB"]));
            }
            set {
                this["uploadToIgniteDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool uploadToFirestore {
            get {
                return ((bool)(this["uploadToFirestore"]));
            }
            set {
                this["uploadToFirestore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool enableFullLogging {
            get {
                return ((bool)(this["enableFullLogging"]));
            }
            set {
                this["enableFullLogging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool onlyRecordPrivateMatches {
            get {
                return ((bool)(this["onlyRecordPrivateMatches"]));
            }
            set {
                this["onlyRecordPrivateMatches"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool batchWrites {
            get {
                return ((bool)(this["batchWrites"]));
            }
            set {
                this["batchWrites"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool useCompression {
            get {
                return ((bool)(this["useCompression"]));
            }
            set {
                this["useCompression"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int targetDeltaTimeIndexFull {
            get {
                return ((int)(this["targetDeltaTimeIndexFull"]));
            }
            set {
                this["targetDeltaTimeIndexFull"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string saveFolder {
            get {
                return ((string)(this["saveFolder"]));
            }
            set {
                this["saveFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int whenToSplitReplays {
            get {
                return ((int)(this["whenToSplitReplays"]));
            }
            set {
                this["whenToSplitReplays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool showConsoleOnStart {
            get {
                return ((bool)(this["showConsoleOnStart"]));
            }
            set {
                this["showConsoleOnStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool outputGameStateEvents {
            get {
                return ((bool)(this["outputGameStateEvents"]));
            }
            set {
                this["outputGameStateEvents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool outputScoreEvents {
            get {
                return ((bool)(this["outputScoreEvents"]));
            }
            set {
                this["outputScoreEvents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool outputStunEvents {
            get {
                return ((bool)(this["outputStunEvents"]));
            }
            set {
                this["outputStunEvents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool outputDiscThrownEvents {
            get {
                return ((bool)(this["outputDiscThrownEvents"]));
            }
            set {
                this["outputDiscThrownEvents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool outputDiscCaughtEvents {
            get {
                return ((bool)(this["outputDiscCaughtEvents"]));
            }
            set {
                this["outputDiscCaughtEvents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool outputDiscStolenEvents {
            get {
                return ((bool)(this["outputDiscStolenEvents"]));
            }
            set {
                this["outputDiscStolenEvents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool outputSaveEvents {
            get {
                return ((bool)(this["outputSaveEvents"]));
            }
            set {
                this["outputSaveEvents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string accessCode {
            get {
                return ((string)(this["accessCode"]));
            }
            set {
                this["accessCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool outputOther {
            get {
                return ((bool)(this["outputOther"]));
            }
            set {
                this["outputOther"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool atlasShowing {
            get {
                return ((bool)(this["atlasShowing"]));
            }
            set {
                this["atlasShowing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpdateSettings {
            get {
                return ((bool)(this["UpdateSettings"]));
            }
            set {
                this["UpdateSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool speedometerStreamerMode {
            get {
                return ((bool)(this["speedometerStreamerMode"]));
            }
            set {
                this["speedometerStreamerMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool playspaceStreamerMode {
            get {
                return ((bool)(this["playspaceStreamerMode"]));
            }
            set {
                this["playspaceStreamerMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool joustTimeTTS {
            get {
                return ((bool)(this["joustTimeTTS"]));
            }
            set {
                this["joustTimeTTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool joustSpeedTTS {
            get {
                return ((bool)(this["joustSpeedTTS"]));
            }
            set {
                this["joustSpeedTTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool serverLocationTTS {
            get {
                return ((bool)(this["serverLocationTTS"]));
            }
            set {
                this["serverLocationTTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool maxBoostSpeedTTS {
            get {
                return ((bool)(this["maxBoostSpeedTTS"]));
            }
            set {
                this["maxBoostSpeedTTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int TTSSpeed {
            get {
                return ((int)(this["TTSSpeed"]));
            }
            set {
                this["TTSSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool playerJoinTTS {
            get {
                return ((bool)(this["playerJoinTTS"]));
            }
            set {
                this["playerJoinTTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool playerLeaveTTS {
            get {
                return ((bool)(this["playerLeaveTTS"]));
            }
            set {
                this["playerLeaveTTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool playerSwitchTeamTTS {
            get {
                return ((bool)(this["playerSwitchTeamTTS"]));
            }
            set {
                this["playerSwitchTeamTTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool tubeExitSpeedTTS {
            get {
                return ((bool)(this["tubeExitSpeedTTS"]));
            }
            set {
                this["tubeExitSpeedTTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string discordOAuthRefreshToken {
            get {
                return ((string)(this["discordOAuthRefreshToken"]));
            }
            set {
                this["discordOAuthRefreshToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool throwSpeedTTS {
            get {
                return ((bool)(this["throwSpeedTTS"]));
            }
            set {
                this["throwSpeedTTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool goalSpeedTTS {
            get {
                return ((bool)(this["goalSpeedTTS"]));
            }
            set {
                this["goalSpeedTTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool goalDistanceTTS {
            get {
                return ((bool)(this["goalDistanceTTS"]));
            }
            set {
                this["goalDistanceTTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string accessMode {
            get {
                return ((string)(this["accessMode"]));
            }
            set {
                this["accessMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int clientHighlightScope {
            get {
                return ((int)(this["clientHighlightScope"]));
            }
            set {
                this["clientHighlightScope"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool clearHighlightsOnExit {
            get {
                return ((bool)(this["clearHighlightsOnExit"]));
            }
            set {
                this["clearHighlightsOnExit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isNVHighlightsEnabled {
            get {
                return ((bool)(this["isNVHighlightsEnabled"]));
            }
            set {
                this["isNVHighlightsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public float nvHighlightsSecondsBefore {
            get {
                return ((float)(this["nvHighlightsSecondsBefore"]));
            }
            set {
                this["nvHighlightsSecondsBefore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float nvHighlightsSecondsAfter {
            get {
                return ((float)(this["nvHighlightsSecondsAfter"]));
            }
            set {
                this["nvHighlightsSecondsAfter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool pausedTTS {
            get {
                return ((bool)(this["pausedTTS"]));
            }
            set {
                this["pausedTTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string alternateEchoVRIP {
            get {
                return ((string)(this["alternateEchoVRIP"]));
            }
            set {
                this["alternateEchoVRIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool nvHighlightsSpectatorRecord {
            get {
                return ((bool)(this["nvHighlightsSpectatorRecord"]));
            }
            set {
                this["nvHighlightsSpectatorRecord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int atlasLinkStyle {
            get {
                return ((int)(this["atlasLinkStyle"]));
            }
            set {
                this["atlasLinkStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool atlasLinkUseAngleBrackets {
            get {
                return ((bool)(this["atlasLinkUseAngleBrackets"]));
            }
            set {
                this["atlasLinkUseAngleBrackets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool firstTimeSetupShown {
            get {
                return ((bool)(this["firstTimeSetupShown"]));
            }
            set {
                this["firstTimeSetupShown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isAutofocusEnabled {
            get {
                return ((bool)(this["isAutofocusEnabled"]));
            }
            set {
                this["isAutofocusEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool loneEchoSubtitlesStreamerMode {
            get {
                return ((bool)(this["loneEchoSubtitlesStreamerMode"]));
            }
            set {
                this["loneEchoSubtitlesStreamerMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string loneEchoPath {
            get {
                return ((string)(this["loneEchoPath"]));
            }
            set {
                this["loneEchoPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double liveWindowTop {
            get {
                return ((double)(this["liveWindowTop"]));
            }
            set {
                this["liveWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double liveWindowLeft {
            get {
                return ((double)(this["liveWindowLeft"]));
            }
            set {
                this["liveWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double settingsWindowTop {
            get {
                return ((double)(this["settingsWindowTop"]));
            }
            set {
                this["settingsWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double settingsWindowLeft {
            get {
                return ((double)(this["settingsWindowLeft"]));
            }
            set {
                this["settingsWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string client_name {
            get {
                return ((string)(this["client_name"]));
            }
            set {
                this["client_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool atlasLinkAppendTeamNames {
            get {
                return ((bool)(this["atlasLinkAppendTeamNames"]));
            }
            set {
                this["atlasLinkAppendTeamNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int atlasHostingVisibility {
            get {
                return ((int)(this["atlasHostingVisibility"]));
            }
            set {
                this["atlasHostingVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool playspaceTTS {
            get {
                return ((bool)(this["playspaceTTS"]));
            }
            set {
                this["playspaceTTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ttsVoice {
            get {
                return ((int)(this["ttsVoice"]));
            }
            set {
                this["ttsVoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ignitebot_spark_upgrade_message_shown {
            get {
                return ((bool)(this["ignitebot_spark_upgrade_message_shown"]));
            }
            set {
                this["ignitebot_spark_upgrade_message_shown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int languageIndex {
            get {
                return ((int)(this["languageIndex"]));
            }
            set {
                this["languageIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int theme {
            get {
                return ((int)(this["theme"]));
            }
            set {
                this["theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public double replayBufferLength {
            get {
                return ((double)(this["replayBufferLength"]));
            }
            set {
                this["replayBufferLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool enableReplayBuffer {
            get {
                return ((bool)(this["enableReplayBuffer"]));
            }
            set {
                this["enableReplayBuffer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool replayClipPlayspace {
            get {
                return ((bool)(this["replayClipPlayspace"]));
            }
            set {
                this["replayClipPlayspace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool replayClipGoal {
            get {
                return ((bool)(this["replayClipGoal"]));
            }
            set {
                this["replayClipGoal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool replayClipSave {
            get {
                return ((bool)(this["replayClipSave"]));
            }
            set {
                this["replayClipSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool betaUpdates {
            get {
                return ((bool)(this["betaUpdates"]));
            }
            set {
                this["betaUpdates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ws://127.0.0.1:4444")]
        public string obsIP {
            get {
                return ((string)(this["obsIP"]));
            }
            set {
                this["obsIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string obsPassword {
            get {
                return ((string)(this["obsPassword"]));
            }
            set {
                this["obsPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool obsAutoconnect {
            get {
                return ((bool)(this["obsAutoconnect"]));
            }
            set {
                this["obsAutoconnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool obsClipPlayspace {
            get {
                return ((bool)(this["obsClipPlayspace"]));
            }
            set {
                this["obsClipPlayspace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool obsClipGoal {
            get {
                return ((bool)(this["obsClipGoal"]));
            }
            set {
                this["obsClipGoal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool obsClipAssist {
            get {
                return ((bool)(this["obsClipAssist"]));
            }
            set {
                this["obsClipAssist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool obsClipSave {
            get {
                return ((bool)(this["obsClipSave"]));
            }
            set {
                this["obsClipSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool replayClipAssist {
            get {
                return ((bool)(this["replayClipAssist"]));
            }
            set {
                this["replayClipAssist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float replayClipSecondsAfter {
            get {
                return ((float)(this["replayClipSecondsAfter"]));
            }
            set {
                this["replayClipSecondsAfter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float obsClipSecondsAfter {
            get {
                return ((float)(this["obsClipSecondsAfter"]));
            }
            set {
                this["obsClipSecondsAfter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public float replayClipSecondsBefore {
            get {
                return ((float)(this["replayClipSecondsBefore"]));
            }
            set {
                this["replayClipSecondsBefore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public float obsClipSecondsBefore {
            get {
                return ((float)(this["obsClipSecondsBefore"]));
            }
            set {
                this["obsClipSecondsBefore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool obsAutostartReplayBuffer {
            get {
                return ((bool)(this["obsAutostartReplayBuffer"]));
            }
            set {
                this["obsAutostartReplayBuffer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool obsClipInterception {
            get {
                return ((bool)(this["obsClipInterception"]));
            }
            set {
                this["obsClipInterception"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool replayClipInterception {
            get {
                return ((bool)(this["replayClipInterception"]));
            }
            set {
                this["replayClipInterception"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int nvHighlightsPlayerScope {
            get {
                return ((int)(this["nvHighlightsPlayerScope"]));
            }
            set {
                this["nvHighlightsPlayerScope"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int replayClipPlayerScope {
            get {
                return ((int)(this["replayClipPlayerScope"]));
            }
            set {
                this["replayClipPlayerScope"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int obsPlayerScope {
            get {
                return ((int)(this["obsPlayerScope"]));
            }
            set {
                this["obsPlayerScope"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool replayClipSpectatorRecord {
            get {
                return ((bool)(this["replayClipSpectatorRecord"]));
            }
            set {
                this["replayClipSpectatorRecord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool obsSpectatorRecord {
            get {
                return ((bool)(this["obsSpectatorRecord"]));
            }
            set {
                this["obsSpectatorRecord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int dashboardItem1 {
            get {
                return ((int)(this["dashboardItem1"]));
            }
            set {
                this["dashboardItem1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useWavenetVoices {
            get {
                return ((bool)(this["useWavenetVoices"]));
            }
            set {
                this["useWavenetVoices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int spectatorCamera {
            get {
                return ((int)(this["spectatorCamera"]));
            }
            set {
                this["spectatorCamera"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hideEchoVRUI {
            get {
                return ((bool)(this["hideEchoVRUI"]));
            }
            set {
                this["hideEchoVRUI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int followClientSpectatorCameraMode {
            get {
                return ((int)(this["followClientSpectatorCameraMode"]));
            }
            set {
                this["followClientSpectatorCameraMode"] = value;
            }
        }
    }
}
